#' Manual cell type classification based on signature gating
#'
#' This function performs a cell type classification based on signature gating.
#'
#' If a list of signatures (sign_a, sign_b...) has been scored with ScoreSignature, cell types (celltype_a, celltype_b...) are defined based on gates (value_xy cutoffs) of the form:
#' "celltype_a = sign_a > value_aa & sign_b < value_ab, celltype_b = sign_b > value_ba & sign_a < value_ab"
#'
#' @param object Seurat object. Must have metadata columns containing signature scores, such as those generated by ScoreSignatures, with names matching any gating filter supplied.
#' @param gates A string (chr) of cell type definitions, with cell types delimited by commas (,). The name of the cell type is given first, followed by equal (=) and a series of gates separated by AND symbol (&). Example: "celltype_a = sign_a > value_aa & sign_b < value_ab, celltype_b = sign_b > value_ba & sign_a < value_ab" where sign_a and sign_b are the names of metadata columns and value_xy are numeric values.
#' @param metadata.name The name of the new metadata column where cell type annotations are stored (Default: celltype)
#' @return A Seurat object with an additional metadata column containing the cell type annotations and Idents() set to these annotations. Cells which do not validate any gate defined are attributed the celltype "None" and cells which pass several gates are labelled "Multiplet".
#' @keywords Cell type classification celltype Classifier manual gates gating
#' @export
#' @examples
#' # After MySeuratObject has been log-normalized in order to contain an RNA>data assay>slot and been augmented with a percent.mito metadata column:
#' # SignatureList should be a list of character vectors, each containing a series of feature/gene names. In this example, the signatures correspond to cell types, and the name of each signature is the name of the corresponding cell type (e.g. Tcell, Bcell, EpithelialCell, Fibroblasts, etc).
#' MySeuratObject <- Impute(MySeuratObject)
#' MySeuratObject <- ScoreSignatures(MySeuratObject,SignatureList)
#' gates <- "celltype_a = sign_a > 1.2 & sign_b < 0.2,
#'           celltype_b = sign_b > 1.1 & sign_a < 0.3"
#' MySeuratObject <- ClassifyManual(MySeuratObject,gates)

ClassifyManual <- function(object, gates, metadata.name="celltype"){
  # Split by cell types:
  gates <- gsub(" ", "", gates)
  gates <- unlist(strsplit(gates,","))
  n_celltypes <- length(gates)

  # Split the cell type name from the gates:
  tmp <- strsplit(gates,"=")
  celltype_names <- unlist(lapply(tmp,"[",1))
  gates2 <- unlist(lapply(tmp,"[",2))

  # Split the gates:
  subgates <- strsplit(gates2,"&")

  # Initialize the cell type filter (start from keep all, to then restrict iteratively for each condition):
  filters <- matrix(data = TRUE, nrow = dim(object)[2], ncol = length(celltype_names), dimnames = list(rownames(object@meta.data),celltype_names))

  # Go through the gates for one cell type at a time, to iteratively restrict the filters:
  for(i in 1:n_celltypes){
    for(j in 1:length(subgates[[i]])){
      gate_tmp <- subgates[[i]][j]
      is_greater <- length(grep(">",gate_tmp))
      if(is_greater){
        sign_use <- strsplit(gate_tmp,">")[[1]][1]
        cutoff <- as.numeric(strsplit(gate_tmp,">")[[1]][2])
        filters[,celltype_names[i]] <- filters[,celltype_names[i]] & object@meta.data[,sign_use] > cutoff
      }else{
        sign_use <- strsplit(gate_tmp,"<")[[1]][1]
        cutoff <- as.numeric(strsplit(gate_tmp,"<")[[1]][2])
        filters[,celltype_names[i]] <- filters[,celltype_names[i]] & object@meta.data[,sign_use] < cutoff
      }
    }
  }

  # Combine the filters to define unique cell types vs None vs Multiplets:
  n_cell_types <- rowSums(filters)
  celltype <- as.vector(matrix("None",nrow = dim(object)[2],ncol = 1))
  for(i in 1:ncol(filters)){
    celltype[as.vector(filters[,i])] <- celltype_names[i]
  }
  celltype[n_cell_types>1] <- "Multiplet"
  object@meta.data[,metadata.name] <- celltype
  Idents(object) <- object[[metadata.name]]
  return(object)
}
